django_restaurant_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurant/', include('restaurant.urls')),
]

restaurant/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    # Ingredient Views
    path('ingredients/', views.IngredientListView.as_view(),
         name='ingredients_list'),
    path('ingredients/create/', views.IngredientCreateView.as_view(),
         name='ingredient_create'),
    path(
        'ingredients/<pk>/delete/',
        views.IngredientDeleteView.as_view(),
        name='ingredient_delete'),
    path('ingredients/<pk>/update/',
         views.IngredientUpdateView.as_view(),
         name='ingredient_update'),

    # MenuItem views
    path('menu/', views.MenuItemListView.as_view(),
         name='menuitems_list'),
    path('menu/create', views.MenuItemCreateView.as_view(),
         name='menuitem_create'),
    path('menu/<pk>/delete', views.MenuItemDeleteView.as_view(),
         name='menuitem_delete'),
    path('menu/<pk>/update', views.MenuItemUpdateView.as_view(),
         name='menuitem_update'),

    # RecipeRequirement views
    path('reciperequirement/create', views.RecipeRequirementCreateView.as_view(),
         name='reciperequirement_create'),
    path('reciperequirement/<pk>/delete', views.RecipeRequirementDeleteView.as_view(),
         name='reciperequirement_delete'),

    # Purchase views
     path('purchase/', views.PurchaseListView.as_view(),
         name='purchases_list'),
    path('purchase/create', views.PurchaseCreateView.as_view(),
         name='purchase_create'),
]

restaurant/models.py
"""Importing models from django.db"""
from django.db import models
from django.urls import reverse


class Ingredient(models.Model):
    """ Ingredients """
    UNITY = 'UN'
    KILOGRAM = 'KG'
    POUNDS = 'LB'
    UNITS = [
        (UNITY, "Unity"),
        (KILOGRAM, "Kilogram"),
        (POUNDS, "Pounds"),
    ]
    name = models.CharField(max_length=32)
    stock = models.DecimalField(max_digits=19, decimal_places=3, default=0)
    unit = models.CharField(max_length=2, choices=UNITS, default=UNITY)
    unit_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.name}: quantity = {self.stock}{self.unit}, \
        price per unit = {self.unit_price}"

    def get_absolute_url(self):
        return reverse('ingredients_list')


class MenuItem(models.Model):
    """ MenuItem """
    name = models.CharField(max_length=32)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.name}: price {self.price}"

    def get_absolute_url(self):
        return reverse('menuitems_list')


class RecipeRequirement(models.Model):
    """ RecipeRequirement """
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.ingredient.name} from {self.menu_item.name}"

    def get_absolute_url(self):
        return reverse('menuitems_list')

class Purchase(models.Model):
    """ Purchase """
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["timestamp"]

    def __str__(self):
        return f"{self.menu_item.name} at {self.timestamp}"

    def get_absolute_url(self):
        return reverse('purchases_list')

restaurant/forms.py
from django import forms
from .models import Ingredient, MenuItem, RecipeRequirement, Purchase


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ('__all__')

class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ('__all__')

class RecipeRequirementForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = ('__all__')

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ('__all__')
    

restaurant/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Ingredient, MenuItem, RecipeRequirement, Purchase
from .forms import IngredientForm, MenuItemForm, RecipeRequirementForm, PurchaseForm


def index(request):
    return render(request, 'restaurant/index.html')

class IngredientListView(ListView):
    model = Ingredient
    template_name = 'restaurant/ingredients_list.html'

class IngredientCreateView(CreateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = 'restaurant/ingredient_create.html'

class IngredientDeleteView(DeleteView):
    model = Ingredient
    success_url = reverse_lazy('ingredients_list')

class IngredientUpdateView(UpdateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = 'restaurant/ingredient_update.html'

class MenuItemListView(ListView):
    model = MenuItem
    template_name = 'restaurant/menuitems_list.html'

class MenuItemCreateView(CreateView):
    model = MenuItem
    form_class = MenuItemForm
    template_name = 'restaurant/menuitem_create.html'

class MenuItemDeleteView(DeleteView):
    model = MenuItem
    success_url = reverse_lazy('menuitems_list')

class MenuItemUpdateView(UpdateView):
    model = MenuItem
    form_class = MenuItemForm
    template_name = 'restaurant/menuitem_update.html'

class RecipeRequirementCreateView(CreateView):
    model = RecipeRequirement
    form_class = RecipeRequirementForm
    template_name = 'restaurant/reciperequirement_create.html'

class RecipeRequirementDeleteView(DeleteView):
    model = RecipeRequirement
    success_url = reverse_lazy('menuitems_list')

class PurchaseListView(ListView):
    model = Purchase
    template_name = 'restaurant/purchases_list.html'

class PurchaseCreateView(CreateView):
    model = Purchase
    form_class = PurchaseForm
    template_name = 'restaurant/purchase_create.html'

restaurant/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant {% block title %}{% endblock  %}</title>
    {% block header %}{% endblock  %}
</head>
<body>
    <h1>Restaurant</h1>
    <ul id="home-links-list">
        <li class="home-links">
            <a href={% url 'index' %}>Home</a>
        </li>
        <li class="home-links">
            <a href={% url 'ingredients_list' %}>Ingredients</a>
        </li>
        <li class="home-links">
            <a href={% url 'menuitems_list' %}>Menu</a>
        </li>
        <li class="home-links">
            <a href={% url 'purchases_list' %}>Purchases</a>
        </li>
    </ul>
    {% block content %}{% endblock  %}
</body>
</html>

restaurant/templates/restaurant/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
{% endblock content %}

restaurant/templates/restaurant/ingredient_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ingredients | Create{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Ingredients</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

restaurant/templates/restaurant/ingredient_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ingredients | Create{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Ingredients</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Ingredient"/>
    </form>
{% endblock content %}

restaurant/templates/restaurant/ingredient_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ingredients | Create{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Ingredients</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update Ingredient"/>
    </form>
{% endblock content %}

restaurant/templates/restaurant/ingredients_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ingredients | List{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Ingredients</h1>
    <a href={% url 'ingredient_create' %}>Add Ingredient</a>
    <table>
        <tr>
            <th>Name</th>
            <th>Stock</th>
            <th>Unit</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        {% for ingredient in object_list %}
        <tr>
            <td>{{ ingredient.name }}</td>
            <td>{{ ingredient.stock }}</td>
            <td>{{ ingredient.unit }}</td>
            <td>{{ ingredient.unit_price }}</td>
            <td>
                <a href={% url 'ingredient_update' ingredient.id %}>Edit</a>
                <a href={% url 'ingredient_delete' ingredient.id %}>Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock content %}

restaurant/templates/restaurant/menuitem_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Menu Item | Delete{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Menu Item</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

restaurant/templates/restaurant/menuitem_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Menu Item | Create{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Menu Item</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Ingredient"/>
    </form>
{% endblock content %}

restaurant/templates/restaurant/menuitem_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Menu Item | Edit{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Menu Item</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update Ingredient"/>
    </form>
{% endblock content %}

restaurant/templates/restaurant/menuitems_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Menu Items | List{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Menu Items</h1>
    <a href={% url 'menuitem_create' %}>Add Menu Item</a>
    <a href={% url 'reciperequirement_create' %}>Add Recipe Requirement</a>
    <table>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Ingredients</th>
            <th>Actions</th>
        </tr>
        {% for menu_item in object_list %}
        <tr>
            <td>{{ menu_item.name }}</td>
            <td>{{ menu_item.price }}</td>
            <td>
                <ul>
                {% for recipe_requirement in menu_item.reciperequirement_set.all %}
                <li>
                    {{ recipe_requirement.ingredient.name }} -
                     {{ recipe_requirement.quantity }} 
                     {{ recipe_requirement.ingredient.unit }}
                     <a href={% url 'reciperequirement_delete' recipe_requirement.id %}>❌</a>
                </li>
                {% endfor %}
                </ul>
            </td>
            <td>
                <a href={% url 'menuitem_update' menu_item.id %}>Edit</a>
                <a href={% url 'menuitem_delete' menu_item.id %}>Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock content %}

restaurant/templates/restaurant/purchase_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Purchase | Create{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Purchase</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Purchase"/>
    </form>
{% endblock content %}

restaurant/templates/restaurant/purchases_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Purchase | List{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Purchase</h1>
    <a href={% url 'purchase_create' %}>Add Purchase</a>
    <table>
        <tr>
            <th>Menu Item</th>
            <th>Price</th>
            <th>Date</th>
        </tr>
        {% for purchase in object_list %}
        <tr>
            <td>{{ purchase.menu_item.name }}</td>
            <td>{{ purchase.menu_item.price }}</td>
            <td>{{ purchase.timestamp }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock content %}

restaurant/templates/restaurant/reciperequirement_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipes | Create{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Recipes</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

restaurant/templates/restaurant/reciperequirement_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipes | Create{% endblock title %}

{% block header %}
    <link rel="stylesheet" href={% static 'restaurant/style.css' %}>
{% endblock header %}

{% block content %}
    <h1>Recipes</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Ingredient"/>
    </form>
{% endblock content %}